		//Calls are now made through kGAMECLASS rather than thisPtr. This allows the compiler to detect if/when a function is inaccessible.

		/**
		 * Possible text arguments in the conditional of a if statement
		 * First, there is an attempt to cast the argument to a Number. If that fails,
		 * a dictionary lookup is performed to see if the argument is in the conditionalOptions[]
		 * object. If that fails, we just fall back to returning 0
		 */
		public  conditionalOptions: Record<string, any> =
		{
				"strength"			: function(): any {return  kGAMECLASS.player.str;},
				"toughness"			: function(): any {return  kGAMECLASS.player.tou;},
				"speed"				: function(): any {return  kGAMECLASS.player.spe;},
				"intelligence"		: function(): any {return  kGAMECLASS.player.inte;},
				"libido"			: function(): any {return  kGAMECLASS.player.lib;},
				"sensitivity"		: function(): any {return  kGAMECLASS.player.sens;},
				"corruption"		: function(): any {return  kGAMECLASS.player.cor;},
				"fatigue"			: function(): any {return  kGAMECLASS.player.fatigue;},
				"hp"				: function(): any {return  kGAMECLASS.player.HP;},
				"hunger"			: function(): any {return  kGAMECLASS.player.hunger;},
				"minute"			: function(): any {return  kGAMECLASS.time.minutes;},
				"hour"				: function(): any {return  kGAMECLASS.time.hours;},
				"days"				: function(): any {return  kGAMECLASS.time.days;},
				"hasarmor"			: function(): any {return  kGAMECLASS.player.armor != ArmorLib.NOTHING;},
				"haslowergarment"	: function(): any {return  kGAMECLASS.player.lowerGarment != UndergarmentLib.NOTHING;},
				"hasweapon"			: function(): any {return  kGAMECLASS.player.weapon != WeaponLib.FISTS;},
				"tallness"			: function(): any {return  kGAMECLASS.player.tallness;},
				"hairlength"		: function(): any {return  kGAMECLASS.player.hair.length;},
				"femininity"		: function(): any {return  kGAMECLASS.player.femininity;},
				"masculinity"		: function(): any {return  100 - kGAMECLASS.player.femininity;},
				"cocks"				: function(): any {return  kGAMECLASS.player.cockTotal();},
				"breastrows"		: function(): any {return  kGAMECLASS.player.bRows();},
				"biggesttitsize"	: function(): any {return  kGAMECLASS.player.biggestTitSize();},
				"vagcapacity"		: function(): any {return  kGAMECLASS.player.vaginalCapacity();},
				"analcapacity"		: function(): any {return  kGAMECLASS.player.analCapacity();},
				"balls"				: function(): any {return  kGAMECLASS.player.balls;},
				"cumquantity"		: function(): any {return  kGAMECLASS.player.cumQ();},
				"biggesttitsize"	: function(): any {return  kGAMECLASS.player.biggestTitSize();},
				"milkquantity"		: function(): any {return  kGAMECLASS.player.lactationQ();},
				"biggestlactation"	: function(): any {return  kGAMECLASS.player.biggestLactation();},
				"hasvagina"			: function(): any {return  kGAMECLASS.player.hasVagina();},
				"istaur"			: function(): any {return  kGAMECLASS.player.isTaur();},
				"ishoofed"			: function(): any {return  kGAMECLASS.player.isHoofed();},
				"iscentaur"			: function(): any {return  kGAMECLASS.player.isCentaur();},
				"isnaga"			: function(): any {return  kGAMECLASS.player.isNaga();},
				"isgoo"				: function(): any {return  kGAMECLASS.player.isGoo();},
				"isbiped"			: function(): any {return  kGAMECLASS.player.isBiped();},
				"hasbreasts"		: function(): any {return  (kGAMECLASS.player.biggestTitSize() >= 1);},
				"hasballs"			: function(): any {return  (kGAMECLASS.player.balls > 0);},
				"hascock"			: function(): any {return  kGAMECLASS.player.hasCock();},
				"hassheath"			: function(): any {return  kGAMECLASS.player.hasSheath();},
				"hasbeak"			: function(): any {return  kGAMECLASS.player.hasBeak();},
				"hascateyes"		: function(): any {return  kGAMECLASS.player.hasCatEyes();},
				"hascatface"		: function(): any {return  kGAMECLASS.player.hasCatFace();},
				"hasclaws"			: function(): any {return  kGAMECLASS.player.hasClaws();},
				"hasdragonneck"		: function(): any {return  kGAMECLASS.player.hasDragonNeck();},
				"hastail"			: function(): any {return  kGAMECLASS.player.hasTail();},
				"neckpos"			: function(): any {return  kGAMECLASS.player.neck.pos;},
				"hasplainskin"		: function(): any {return  kGAMECLASS.player.hasPlainSkin();},
				"hasfur"			: function(): any {return  kGAMECLASS.player.hasFur();},
				"haswool"			: function(): any {return  kGAMECLASS.player.hasWool();},
				"hasfeathers"		: function(): any {return  kGAMECLASS.player.hasFeathers();},
				"hasfurryunderbody"	: function(): any {return  kGAMECLASS.player.hasFurryUnderBody();},
				"isfurry"			: function(): any {return  kGAMECLASS.player.isFurry();},
				"isfluffy"			: function(): any {return  kGAMECLASS.player.isFluffy();},
				"isgenderless"		: function(): any {return  (kGAMECLASS.player.isGenderless());},
				"ismale"			: function(): any {return  (kGAMECLASS.player.isMale());},
				"isfemale"			: function(): any {return  (kGAMECLASS.player.isFemale());},
				"isherm"			: function(): any {return  (kGAMECLASS.player.isHerm());},
				"ismaleorherm"		: function(): any {return  (kGAMECLASS.player.isMaleOrHerm());},
				"isfemaleorherm"	: function(): any {return  (kGAMECLASS.player.isFemaleOrHerm());},
				"cumnormal"			: function(): any {return  (kGAMECLASS.player.cumQ() <= 150);},
				"cummedium"			: function(): any {return  (kGAMECLASS.player.cumQ() > 150 && kGAMECLASS.player.cumQ() <= 350);},
				"cumhigh"			: function(): any {return  (kGAMECLASS.player.cumQ() > 350 && kGAMECLASS.player.cumQ() <= 1000);},
				"cumveryhigh"		: function(): any {return  (kGAMECLASS.player.cumQ() > 1000 && kGAMECLASS.player.cumQ() <= 2500);},
				"cumextreme"		: function(): any {return  (kGAMECLASS.player.cumQ() > 2500);},
				"issquirter"		: function(): any {return  (kGAMECLASS.player.wetness() >= 4);},
				"vaginalwetness"	: function(): any {return  kGAMECLASS.player.wetness();},
				"anallooseness"		: function(): any {return  kGAMECLASS.player.ass.analLooseness;},
				"buttrating"		: function(): any {return  kGAMECLASS.player.butt.rating;},
				"ispregnant"		: function(): any {return  (kGAMECLASS.player.pregnancyIncubation > 0);},
				"isbuttpregnant"	: function(): any {return  (kGAMECLASS.player.buttPregnancyIncubation > 0);},
				"hasnipplecunts"	: function(): any {return  kGAMECLASS.player.hasFuckableNipples();},
				"totalnipples"		: function(): any {return  kGAMECLASS.player.totalNipples();},
				"canfly"			: function(): any {return  kGAMECLASS.player.canFly();},
				"hasovipositor"		: function(): any {return  kGAMECLASS.player.hasOvipositor();},
				"islactating"		: function(): any {return  (kGAMECLASS.player.lactationQ() > 0);},
				"isbimbo"			: function(): any {return  kGAMECLASS.player.isBimbo();},
				"true"				: function(): any {return  true;},
				"false"				: function(): any {return  false;},
				
				//Prison
				"esteem"			: function(): any {return  kGAMECLASS.player.esteem; },
				"obey"				: function(): any {return  kGAMECLASS.player.obey; },
				"will"				: function(): any {return  kGAMECLASS.player.will; },

				//---[NPCs]---
				//Joy
				"joyhascock"		: function(): any {return  kGAMECLASS.joyScene.joyHasCock(); },

				//Tel Adre
				"bakerytalkedroot"	: function(): any {return  kGAMECLASS.flags[kFLAGS.MINO_CHEF_TALKED_RED_RIVER_ROOT] > 0; }
			}
