import { BaseContent } from "../BaseContent";
import { IncubiDraft } from "./Consumables/IncubiDraft";
import { SuccubisDream } from "./Consumables/SuccubisDream";
import { SuccubisDelight } from "./Consumables/SuccubisDelight";
import { SuccubiMilk } from "./Consumables/SuccubiMilk";
import { HairDye } from "./Consumables/HairDye";
import { SkinOil } from "./Consumables/SkinOil";
import { BodyLotion } from "./Consumables/BodyLotion";
import { BlackRubberEgg } from "./Consumables/BlackRubberEgg";
import { BlueEgg } from "./Consumables/BlueEgg";
import { BrownEgg } from "./Consumables/BrownEgg";
import { PinkEgg } from "./Consumables/PinkEgg";
import { PurpleEgg } from "./Consumables/PurpleEgg";
import { WhiteEgg } from "./Consumables/WhiteEgg";
import { EmberEgg } from "./Consumables/EmberEgg";
import { NeonPinkEgg } from "./Consumables/NeonPinkEgg";
import { BlackCatBeer } from "./Consumables/BlackCatBeer";
import { BehemothCum } from "./Consumables/BehemothCum";
import { BimboChampagne } from "./Consumables/BimboChampagne";
import { CumBread } from "./Consumables/CumBread";
import { GiantChocolateCupcake } from "./Consumables/GiantChocolateCupcake";
import { FishFillet } from "./Consumables/FishFillet";
import { FrothyBeer } from "./Consumables/FrothyBeer";
import { GodMead } from "./Consumables/GodMead";
import { HardBiscuits } from "./Consumables/HardBiscuits";
import { IsabellaMilk } from "./Consumables/IsabellaMilk";
import { MarbleMilk } from "./Consumables/MarbleMilk";
import { MinotaurCum } from "./Consumables/MinotaurCum";
import { PrisonBread } from "./Consumables/PrisonBread";
import { PhoukaWhiskey } from "./Consumables/PhoukaWhiskey";
import { ProMead } from "./Consumables/ProMead";
import { PurityPeach } from "./Consumables/PurityPeach";
import { SheepMilk } from "./Consumables/SheepMilk";
import { SpringWater } from "./Consumables/SpringWater";
import { TrailMix } from "./Consumables/TrailMix";
import { UrtaCum } from "./Consumables/UrtaCum";
import { WinterPudding } from "./Consumables/WinterPudding";
import { Reducto } from "./Consumables/Reducto";
import { GroPlus } from "./Consumables/GroPlus";
import { BlackSpellBook } from "./Consumables/BlackSpellBook";
import { WhiteSpellBook } from "./Consumables/WhiteSpellBook";
import { BimboLiqueur } from "./Consumables/BimboLiqueur";
import { BroBrew } from "./Consumables/BroBrew";
import { SuperHummus } from "./Consumables/SuperHummus";
import { PurePearl } from "./Consumables/PurePearl";
import { AkbalSaliva } from "./Consumables/AkbalSaliva";
import { Mint } from "./Consumables/Mint";
import { CeruleanPotion } from "./Consumables/CeruleanPotion";
import { Clovis } from "./Consumables/Clovis";
import { Coal } from "./Consumables/Coal";
import { DeBimbo } from "./Consumables/DeBimbo";
import { HairExtensionSerum } from "./Consumables/HairExtensionSerum";
import { LustDraft } from "./Consumables/LustDraft";
import { HealPill } from "./Consumables/HealPill";
import { HerbalContraceptive } from "./Consumables/HerbalContraceptive";
import { IceShard } from "./Consumables/IceShard";
import { KitsuneGift } from "./Consumables/KitsuneGift";
import { Lactaid } from "./Consumables/Lactaid";
import { LustStick } from "./Consumables/LustStick";
import { MilkPotion } from "./Consumables/MilkPotion";
import { NumbingOil } from "./Consumables/NumbingOil";
import { NumbRocks } from "./Consumables/NumbRocks";
import { OvipositionElixir } from "./Consumables/OvipositionElixir";
import { OvipositionMax } from "./Consumables/OvipositionMax";
import { PeppermintWhite } from "./Consumables/PeppermintWhite";
import { PurityPhilter } from "./Consumables/PurityPhilter";
import { PrincessPucker } from "./Consumables/PrincessPucker";
import { SensitivityDraft } from "./Consumables/SensitivityDraft";
import { ScholarsTea } from "./Consumables/ScholarsTea";
import { VitalityTincture } from "./Consumables/VitalityTincture";
import { WingStick } from "./Consumables/WingStick";
import { SweetGossamer } from "./Consumables/SweetGossamer";
import { PigTruffle } from "./Consumables/PigTruffle";
import { EmberTFs } from "./Consumables/EmberTFs";
import { ShriveledTentacle } from "./Consumables/ShriveledTentacle";
import { EchidnaCake } from "./Consumables/EchidnaCake";
import { Ectoplasm } from "./Consumables/Ectoplasm";
import { Equinum } from "./Consumables/Equinum";
import { FoxBerry } from "./Consumables/FoxBerry";
import { FerretFruit } from "./Consumables/FerretFruit";
import { FoxJewel } from "./Consumables/FoxJewel";
import { GoldenRind } from "./Consumables/GoldenRind";
import { GoldenSeed } from "./Consumables/GoldenSeed";
import { GoblinAle } from "./Consumables/GoblinAle";
import { RegularHummus } from "./Consumables/RegularHummus";
import { ImpFood } from "./Consumables/ImpFood";
import { KangaFruit } from "./Consumables/KangaFruit";
import { LaBova } from "./Consumables/LaBova";
import { MouseCocoa } from "./Consumables/MouseCocoa";
import { MinotaurBlood } from "./Consumables/MinotaurBlood";
import { OculumArachnae } from "./Consumables/OculumArachnae";
import { PurpleFruit } from "./Consumables/PurpleFruit";
import { RedRiverRoot } from "./Consumables/RedRiverRoot";
import { Reptilum } from "./Consumables/Reptilum";
import { RhinoSteak } from "./Consumables/RhinoSteak";
import { RingtailFig } from "./Consumables/RingtailFig";
import { RizzaRoot } from "./Consumables/RizzaRoot";
import { Salamanderfirewater } from "./Consumables/Salamanderfirewater";
import { SatyrWine } from "./Consumables/SatyrWine";
import { SharkTooth } from "./Consumables/SharkTooth";
import { SnakeOil } from "./Consumables/SnakeOil";
import { Taurinum } from "./Consumables/Taurinum";
import { TonOTrice } from "./Consumables/TonOTrice";
import { TrapOil } from "./Consumables/TrapOil";
import { TatteredScroll } from "./Consumables/TatteredScroll";
import { WhiskerFruit } from "./Consumables/WhiskerFruit";
import { WetCloth } from "./Consumables/WetCloth";
import { WolfPepper } from "./Consumables/WolfPepper";
import { UnlabeledBrownMilkBottle } from "./Consumables/UnlabeledBrownMilkBottle";
import { BeeHoney } from "./Consumables/BeeHoney";
import { CaninePepper } from "./Consumables/CaninePepper";

/**
 * Created by aimozg on 10.01.14.
 */

export class ConsumableLib extends BaseContent {
    // 		public var consumableItems: any[] = [];
    public static DEFAULT_VALUE: number = 6;
    // 		DEMONIC POTIONS
    // Tainted
    public INCUBID = new IncubiDraft(IncubiDraft.TAINTED);
    public S_DREAM = new SuccubisDream();
    public SDELITE = new SuccubisDelight(SuccubisDelight.TAINTED);
    public SUCMILK = new SuccubiMilk(SuccubiMilk.TAINTED);
    // Untainted
    public P_DRAFT = new IncubiDraft(IncubiDraft.PURIFIED);
    public P_S_MLK = new SuccubiMilk(SuccubiMilk.PURIFIED);
    public PSDELIT = new SuccubisDelight(SuccubisDelight.PURIFIED);
    // 		DYES
    public AUBURND: HairDye = new HairDye("AuburnD", "Auburn");
    public BLACK_D: HairDye = new HairDye("Black D", "Black");
    public BLOND_D: HairDye = new HairDye("Blond D", "Blond");
    public BLUEDYE: HairDye = new HairDye("BlueDye", "Blue");
    public BROWN_D: HairDye = new HairDye("Brown D", "Brown");
    public GRAYDYE: HairDye = new HairDye("GrayDye", "Gray");
    public GREEN_D: HairDye = new HairDye("Green D", "Green");
    public ORANGDY: HairDye = new HairDye("OrangDy", "Orange");
    public PINKDYE: HairDye = new HairDye("PinkDye", "Pink");
    public PURPDYE: HairDye = new HairDye("PurpDye", "Purple");
    public RAINDYE: HairDye = new HairDye("RainDye", "Rainbow");
    public RED_DYE: HairDye = new HairDye("Red Dye", "Red");
    public RUSSDYE: HairDye = new HairDye("RussetD", "Russet");
    public YELLODY: HairDye = new HairDye("YelloDy", "Yellow");
    public WHITEDY: HairDye = new HairDye("WhiteDy", "White");
    // 		SKIN OILS
    public DARK_OL: SkinOil = new SkinOil("DarkOil", "Dark");
    public EBONYOL: SkinOil = new SkinOil("EbonyOl", "Ebony");
    public FAIR_OL: SkinOil = new SkinOil("FairOil", "Fair");
    public LIGHTOL: SkinOil = new SkinOil("LightOl", "Light");
    public MAHOGOL: SkinOil = new SkinOil("MahogOl", "Mahogany");
    public OLIVEOL: SkinOil = new SkinOil("OliveOl", "Olive");
    public RUSS_OL: SkinOil = new SkinOil("RussOil", "Russet");
    public RED__OL: SkinOil = new SkinOil("Red Oil", "Red");
    public ORANGOL: SkinOil = new SkinOil("OranOil", "Orange");
    public YELLOOL: SkinOil = new SkinOil("YeloOil", "Yellow");
    public GREENOL: SkinOil = new SkinOil("GrenOil", "Green");
    public WHITEOL: SkinOil = new SkinOil("WhitOil", "White");
    public BLUE_OL: SkinOil = new SkinOil("BlueOil", "Blue");
    public BLACKOL: SkinOil = new SkinOil("BlakOil", "Black");
    public PURPLOL: SkinOil = new SkinOil("PurpOil", "Purple");
    public SILVROL: SkinOil = new SkinOil("SlvrOil", "Silver");
    public YELGROL: SkinOil = new SkinOil("YlGrOil", "Yellow Green");
    public SPRGROL: SkinOil = new SkinOil("SpGrOil", "Spring Green");
    public CYAN_OL: SkinOil = new SkinOil("CyanOil", "Cyan");
    public OCBLUOL: SkinOil = new SkinOil("OBluOil", "Ocean Blue");
    public ELVIOOL: SkinOil = new SkinOil("EVioOil", "Electric Violet");
    public MAGENOL: SkinOil = new SkinOil("MagenOl", "Magenta");
    public DPPNKOL: SkinOil = new SkinOil("DPnkOil", "Deep Pink");
    public PINK_OL: SkinOil = new SkinOil("PinkOil", "Pink");
    // 		BODY LOTIONS
    public CLEARLN: BodyLotion = new BodyLotion("ClearLn", "Clear", "smooth thick creamy liquid");
    public ROUGHLN: BodyLotion = new BodyLotion("RoughLn", "Rough", "thick abrasive cream");
    public SEXY_LN: BodyLotion = new BodyLotion("SexyLtn", "Sexy", "pretty cream like substance");
    public SMTH_LN: BodyLotion = new BodyLotion("SmthLtn", "Smooth", "smooth thick creamy liquid");
    // 		EGGS
    // Small
    public BLACKEG = new BlackRubberEgg(BlackRubberEgg.SMALL);
    public BLUEEGG = new BlueEgg(BlueEgg.SMALL);
    public BROWNEG = new BrownEgg(BrownEgg.SMALL);
    public PINKEGG = new PinkEgg(PinkEgg.SMALL);
    public PURPLEG = new PurpleEgg(PurpleEgg.SMALL);
    public WHITEEG = new WhiteEgg(WhiteEgg.SMALL);
    // Large
    public L_BLKEG = new BlackRubberEgg(BlackRubberEgg.LARGE);
    public L_BLUEG = new BlueEgg(BlueEgg.LARGE);
    public L_BRNEG = new BrownEgg(BrownEgg.LARGE);
    public L_PNKEG = new PinkEgg(PinkEgg.LARGE);
    public L_PRPEG = new PurpleEgg(PurpleEgg.LARGE);
    public L_WHTEG = new WhiteEgg(WhiteEgg.LARGE);
    // Others
    public DRGNEGG = new EmberEgg();
    public NPNKEGG: NeonPinkEgg = new NeonPinkEgg();

    // 		FOOD & BEVERAGES
    public BC_BEER: BlackCatBeer = new BlackCatBeer();
    public BHMTCUM = new BehemothCum();
    public BIMBOCH: BimboChampagne = new BimboChampagne();
    public C_BREAD = new CumBread();
    public CCUPCAK = new GiantChocolateCupcake();
    public FISHFIL = new FishFillet();
    public FR_BEER = new FrothyBeer();
    public GODMEAD = new GodMead();
    public H_BISCU = new HardBiscuits();
    public IZYMILK = new IsabellaMilk();
    public M__MILK = new MarbleMilk();
    public MINOCUM = new MinotaurCum(MinotaurCum.STANDARD);
    public P_BREAD = new PrisonBread();
    public P_M_CUM = new MinotaurCum(MinotaurCum.PURIFIED);
    public P_WHSKY: PhoukaWhiskey = new PhoukaWhiskey();
    public PROMEAD = new ProMead();
    public PURPEAC = new PurityPeach();
    public SHEEPMK = new SheepMilk();
    public S_WATER = new SpringWater();
    public TRAILMX = new TrailMix();
    public URTACUM = new UrtaCum();
    public W_PDDNG = new WinterPudding();
    // 		GROWERS/SHRINKERS
    public REDUCTO = new Reducto();
    public GROPLUS = new GroPlus();
    // 		MAGIC BOOKS
    public B__BOOK = new BlackSpellBook();
    public W__BOOK = new WhiteSpellBook();
    // 		RARE ITEMS (Permanent effects, gives perks on consumption)
    public BIMBOLQ = new BimboLiqueur();
    public BROBREW = new BroBrew();
    public HUMMUS2 = new SuperHummus();
    public P_PEARL = new PurePearl();
    // 		NON-TRANSFORMATIVE ITEMS
    public AKBALSL = new AkbalSaliva();
    public C__MINT = new Mint();
    public CERUL_P = new CeruleanPotion();
    public CLOVERS = new Clovis();
    public COAL___ = new Coal();
    public DEBIMBO: DeBimbo = new DeBimbo();
    public EXTSERM: HairExtensionSerum = new HairExtensionSerum();
    public F_DRAFT = new LustDraft(LustDraft.ENHANCED);
    public H_PILL = new HealPill();
    public HRBCNT = new HerbalContraceptive();
    public ICICLE_ = new IceShard();
    public KITGIFT: KitsuneGift = new KitsuneGift();
    public L_DRAFT = new LustDraft(LustDraft.STANDARD);
    public LACTAID = new Lactaid();
    public LUSTSTK: LustStick = new LustStick();
    public MILKPTN = new MilkPotion();
    public NUMBOIL = new NumbingOil();
    public NUMBROX = new NumbRocks();
    public OVIELIX: OvipositionElixir = new OvipositionElixir();
    public OVI_MAX: OvipositionMax = new OvipositionMax();
    public PEPPWHT = new PeppermintWhite();
    public PPHILTR = new PurityPhilter();
    public PRNPKR = new PrincessPucker();
    public SENSDRF = new SensitivityDraft();
    public SMART_T = new ScholarsTea();
    public VITAL_T = new VitalityTincture();
    public W_STICK: WingStick = new WingStick();
    // 		TRANSFORMATIVE ITEMS
    public B_GOSSR = new SweetGossamer(SweetGossamer.DRIDER);
    public BOARTRU = new PigTruffle(true);
    public DRAKHRT: EmberTFs = new EmberTFs(1);
    public DRYTENT = new ShriveledTentacle();
    public ECHIDCK = new EchidnaCake();
    public ECTOPLS = new Ectoplasm();
    public EMBERBL: EmberTFs = new EmberTFs();
    public EQUINUM = new Equinum();
    public FOXBERY = new FoxBerry(FoxBerry.STANDARD);
    public FRRTFRT = new FerretFruit();
    public FOXJEWL = new FoxJewel(FoxJewel.STANDARD);
    public GLDRIND: GoldenRind = new GoldenRind();
    public GLDSEED = new GoldenSeed(GoldenSeed.STANDARD);
    public GOB_ALE = new GoblinAle();
    public HUMMUS_ = new RegularHummus();
    public IMPFOOD = new ImpFood();
    public KANGAFT = new KangaFruit(KangaFruit.STANDARD);
    public LABOVA_: LaBova = new LaBova(LaBova.STANDARD);
    public MAGSEED = new GoldenSeed(GoldenSeed.ENHANCED);
    public MGHTYVG = new KangaFruit(KangaFruit.ENHANCED);
    public MOUSECO = new MouseCocoa();
    public MINOBLO = new MinotaurBlood();
    public MYSTJWL = new FoxJewel(FoxJewel.MYSTIC);
    public OCULUMA = new OculumArachnae();
    public P_LBOVA = new LaBova(LaBova.PURIFIED);
    public PIGTRUF = new PigTruffle(false);
    public PRFRUIT = new PurpleFruit();
    public PROBOVA = new LaBova(LaBova.ENHANCED);
    public RDRROOT = new RedRiverRoot();
    public REPTLUM = new Reptilum();
    public RHINOST = new RhinoSteak();
    public RINGFIG = new RingtailFig();
    public RIZZART = new RizzaRoot();
    public S_GOSSR = new SweetGossamer(SweetGossamer.SPIDER);
    public SALAMFW = new Salamanderfirewater();
    public SATYR_W = new SatyrWine();
    public SHARK_T = new SharkTooth(false);
    public SNAKOIL = new SnakeOil();
    public TAURICO = new Taurinum();
    public TOTRICE = new TonOTrice();
    public TRAPOIL = new TrapOil();
    public TSCROLL = new TatteredScroll();
    public TSTOOTH = new SharkTooth(true);
    public VIXVIGR = new FoxBerry(FoxBerry.ENHANCED);
    public W_FRUIT = new WhiskerFruit();
    public WETCLTH = new WetCloth();
    public WOLF_PP = new WolfPepper();
    public UBMBOTT = new UnlabeledBrownMilkBottle();
    // Bzzzzt! Bee honey ahoy!
    public BEEHONY = new BeeHoney(false, false);
    public PURHONY = new BeeHoney(true, false);
    public SPHONEY = new BeeHoney(false, true);
    // Canine puppers, I mean peppers
    public CANINEP = new CaninePepper(CaninePepper.STANDARD);
    public LARGEPP = new CaninePepper(CaninePepper.LARGE);
    public DBLPEPP = new CaninePepper(CaninePepper.DOUBLE);
    public BLACKPP = new CaninePepper(CaninePepper.BLACK);
    public KNOTTYP = new CaninePepper(CaninePepper.KNOTTY);
    public BULBYPP = new CaninePepper(CaninePepper.BULBY);

    public LARGE_EGGS: any[] = [L_BLKEG, L_BLUEG, L_BRNEG, L_PNKEG, L_PRPEG, L_WHTEG];
    public SMALL_EGGS: any[] = [BLACKEG, BLUEEGG, BROWNEG, PINKEGG, PURPLEG, WHITEEG];
}
