
	/**
	 * IMPORTANT NOTE: any You can rename the constants BUT NOT the string ids (they are stored in saves).
	 */
	export class StatusEffects
	{
		// Non-combat player perks
		public static  AllNaturalOnaholeUsed:StatusEffectType = mk("all-natural onahole used");
		public static  AndysSmoke:StatusEffectType = mk("Andy's Smoke"); //v1: Hours; v2: Speed; v3: Intelligence
		public static  AteEgg:StatusEffectType = mk("ateEgg");
		public static  AnemoneArousal:StatusEffectType = mk("Anemone Arousal");
		public static  BimboChampagne:StatusEffectType = mk("Bimbo Champagne");
		public static  Birthed:StatusEffectType = mk("Birthed");
		public static  BirthedImps:StatusEffectType = mk("Birthed Imps");
		public static  BlackCatBeer:StatusEffectType = mk("Black Cat Beer");
		public static  BlackNipples:StatusEffectType = mk("Black Nipples");
		public static  BlowjobOn:StatusEffectType = mk("BlowjobOn");
		public static  BoatDiscovery:StatusEffectType = mk("Boat Discovery");
		public static  BonusACapacity:StatusEffectType = mk("Bonus aCapacity");
		public static  BonusVCapacity:StatusEffectType = mk("Bonus vCapacity");
		public static  BottledMilk:StatusEffectType = mk("Bottled Milk");
		public static  BreastsMilked:StatusEffectType = mk("Breasts Milked");
		public static  BSwordBroken:StatusEffectType = mk("BSwordBroken");
		public static  BuiltMilker:StatusEffectType = mk("BUILT: Milker");
		public static  BurpChanged:StatusEffectType = mk("Burp Changed");
		public static  ButtStretched:StatusEffectType = mk("ButtStretched");
		public static  CampAnemoneTrigger:StatusEffectType = mk("Camp Anemone Trigger");
		public static  CampMarble:StatusEffectType = mk("Camp Marble");
		public static  CampRathazul:StatusEffectType = mk("Camp Rathazul");
		public static  ClaraCombatRounds:StatusEffectType = mk("Clara Combat Rounds");
		public static  ClaraFoughtInCamp:StatusEffectType = mk("Clara Fought In Camp");
		public static  CockPumped:StatusEffectType = mk("Cock Pumped");
		public static  Contraceptives:StatusEffectType = mk("Contraceptives");
		public static  CuntStretched:StatusEffectType = mk("CuntStretched"); //Used only for compatibility with old save files, replaced with attribute on vagina class
		public static  DefenseCanopy:StatusEffectType = mk("Defense: Canopy");
		public static  DeluxeOnaholeUsed:StatusEffectType = mk("deluxe onahole used");
		public static  DogWarning:StatusEffectType = mk("dog warning");
		public static  DragonBreathBoost:StatusEffectType = mk("Dragon Breath Boost");
		public static  DragonBreathCooldown:StatusEffectType = mk("Dragon Breath Cooldown");
		public static  Dysfunction:StatusEffectType = mk("dysfunction");
		public static  Edryn:StatusEffectType = mk("Edryn");
		public static  Eggchest:StatusEffectType = mk("eggchest");
		public static  Eggs:StatusEffectType = mk("eggs");
		public static  EmberFuckCooldown:StatusEffectType = mk("ember fuck cooldown");
		public static  EmberMilk:StatusEffectType = mk("Ember's Milk");
		public static  EmberNapping:StatusEffectType = mk("Ember Napping");
		public static  EverRapedJojo:StatusEffectType = mk("Ever Raped Jojo");
		public static  Exgartuan:StatusEffectType = mk("Exgartuan");
		public static  ExploredDeepwoods:StatusEffectType = mk("exploredDeepwoods");
		public static  FaerieFemFuck:StatusEffectType = mk("Faerie Fem Fuck");
		public static  FaerieFucked:StatusEffectType = mk("Faerie Fucked");
		public static  FappedGenderless:StatusEffectType = mk("fapped genderless");
		public static  Feeder:StatusEffectType = mk("Feeder");
		public static  Fertilized:StatusEffectType = mk("Fertilized");
		public static  FetishOn:StatusEffectType = mk("fetishON");
		public static  FuckedMarble:StatusEffectType = mk("FuckedMarble");
		public static  Fullness:StatusEffectType = mk("Fullness"); //Alternative to hunger
		public static  Goojob:StatusEffectType = mk("GOOJOB");
		public static  GooStuffed:StatusEffectType = mk("gooStuffed");
		public static  Groundpound:StatusEffectType = mk("Groundpound");
		public static  HairdresserMeeting:StatusEffectType = mk("hairdresser meeting");
		public static  Hangover:StatusEffectType = mk("Hangover");
		public static  Heat:StatusEffectType = mk("heat");
		public static  HorseWarning:StatusEffectType = mk("horse warning");
		public static  ImmolationSpell:StatusEffectType = mk("Immolation Spell");
		public static  ImpGangBang:StatusEffectType = mk("Imp GangBang");
		public static  Infested:StatusEffectType = mk("infested");
		public static  IzmaBlowing:StatusEffectType = mk("IzmaBlowing");
		public static  IzumisPipeSmoke:StatusEffectType = mk("Izumis Pipe Smoke");
		public static  JerkingIzma:StatusEffectType = mk("JerkingIzma");
		public static  Jizzpants:StatusEffectType = mk("Jizzpants");
		public static  JojoMeditationCount:StatusEffectType = mk("Jojo Meditation Count");
		public static  JojoNightWatch:StatusEffectType = mk("JojoNightWatch");
		public static  JojoTFOffer:StatusEffectType = mk("JojoTFOffer");
		public static  Kelt:StatusEffectType = mk("Kelt");
		public static  KeltBJ:StatusEffectType = mk("KeltBJ");
		public static  KeltBadEndWarning:StatusEffectType = mk("Kelt Bad End Warning");
		public static  KeltOff:StatusEffectType = mk("KeltOff");
		public static  KnowsArouse:StatusEffectType = mk("Knows Arouse");
		public static  KnowsBlind:StatusEffectType = mk("Knows Blind");
		public static  KnowsCharge:StatusEffectType = mk("Knows Charge");
		public static  KnowsHeal:StatusEffectType = mk("Knows Heal");
		public static  KnowsMight:StatusEffectType = mk("Knows Might");
		public static  KnowsWhitefire:StatusEffectType = mk("Knows Whitefire");
		public static  KnowsBlackfire:StatusEffectType = mk("Knows Blackfire");
		public static  LactationEndurance:StatusEffectType = mk("Lactation Endurance");
		public static  LactationReduction:StatusEffectType = mk("Lactation Reduction");
		public static  LactationReduc0:StatusEffectType = mk("Lactation Reduc0");
		public static  LactationReduc1:StatusEffectType = mk("Lactation Reduc1");
		public static  LactationReduc2:StatusEffectType = mk("Lactation Reduc2");
		public static  LactationReduc3:StatusEffectType = mk("Lactation Reduc3");
		public static  LootEgg:StatusEffectType = mk("lootEgg");
		public static  LostVillagerSpecial:StatusEffectType = mk("lostVillagerSpecial");
		public static  Luststick:StatusEffectType = mk("Luststick");
		public static  LustStickApplied:StatusEffectType = mk("Lust Stick Applied");
		public static  LustyTongue:StatusEffectType = mk("LustyTongue");
		public static  MalonVisitedPostAddiction:StatusEffectType = mk("Malon Visited Post Addiction");
		public static  Marble:StatusEffectType = mk("Marble");
		public static  MarbleHasItem:StatusEffectType = mk("MarbleHasItem");
		public static  MarbleItemCooldown:StatusEffectType = mk("MarbleItemCooldown");
		public static  MarbleRapeAttempted:StatusEffectType = mk("Marble Rape Attempted");
		public static  MarblesMilk:StatusEffectType = mk("Marbles Milk");
		public static  MarbleSpecials:StatusEffectType = mk("MarbleSpecials");
		public static  MarbleWithdrawl:StatusEffectType = mk("MarbleWithdrawl");
		public static  Meditated:StatusEffectType = mk("Meditated"); // DEPRECATED
		public static  MeanToNaga:StatusEffectType = mk("MeanToNaga");
		public static  MeetWanderer:StatusEffectType = mk("meet wanderer");
		public static  MetRathazul:StatusEffectType = mk("metRathazul");
		public static  MetWorms:StatusEffectType = mk("metWorms");
		public static  MetWhitney:StatusEffectType = mk("Met Whitney");
		public static  Milked:StatusEffectType = mk("Milked");
		public static  MinoPlusCowgirl:StatusEffectType = mk("Mino + Cowgirl");
		public static  Naga:StatusEffectType = mk("Naga");
		public static  NakedOn:StatusEffectType = mk("NakedOn");
		public static  NoJojo:StatusEffectType = mk("noJojo");
		public static  NoMoreMarble:StatusEffectType = mk("No More Marble");
		public static  Oswald:StatusEffectType = mk("Oswald");
		public static  PlainOnaholeUsed:StatusEffectType = mk("plain onahole used");
		public static  PhoukaWhiskeyAffect:StatusEffectType = mk("PhoukaWhiskeyAffect");
		public static  PostAkbalSubmission:StatusEffectType = mk("Post Akbal Submission");
		public static  PostAnemoneBeatdown:StatusEffectType = mk("Post Anemone Beatdown");
		public static  PureCampJojo:StatusEffectType = mk("PureCampJojo");
		public static  RathazulArmor:StatusEffectType = mk("RathazulArmor");
		public static  RepeatSuccubi:StatusEffectType = mk("repeatSuccubi");
		public static  Rut:StatusEffectType = mk("rut");
		public static  SharkGirl:StatusEffectType = mk("Shark-Girl");
		public static  ShieldingSpell:StatusEffectType = mk("Shielding Spell");
		public static  SlimeCraving:StatusEffectType = mk("Slime Craving");
		public static  SlimeCravingFeed:StatusEffectType = mk("Slime Craving Feed");
		public static  SlimeCravingOutput:StatusEffectType = mk("Slime Craving Output");
		public static  SuccubiFirst:StatusEffectType = mk("SuccubiFirst");
		public static  SuccubiNight:StatusEffectType = mk("succubiNight");
		public static  TakenGroPlus:StatusEffectType = mk("TakenGro+");
		public static  TakenLactaid:StatusEffectType = mk("TakenLactaid");
		public static  Tamani:StatusEffectType = mk("Tamani");									//Used only for compatibility with old save files, otherwise no longer in use
		public static  TamaniFemaleEncounter:StatusEffectType = mk("Tamani Female Encounter");	//Used only for compatibility with old save files, otherwise no longer in use
		public static  TelAdre:StatusEffectType = mk("Tel'Adre");
		public static  TentacleBadEndCounter:StatusEffectType = mk("TentacleBadEndCounter");
		public static  TentacleJojo:StatusEffectType = mk("Tentacle Jojo");
		public static  TensionReleased:StatusEffectType = mk("TensionReleased");
		public static  TF2:StatusEffectType = mk("TF2");
		public static  TookBlessedSword:StatusEffectType = mk("Took Blessed Sword");
		
		//Old status plots. DEPRECATED, DO NOT USE. Currently cannot be removed without breaking existing saves.
		public static  DungeonShutDown:StatusEffectType = mk("DungeonShutDown");
		public static  FactoryOmnibusDefeated:StatusEffectType = mk("FactoryOmnibusDefeated");
		public static  FactoryOverload:StatusEffectType = mk("FactoryOverload");
		public static  FactoryIncubusDefeated:StatusEffectType = mk("FactoryIncubusDefeated");
		public static  FoundFactory:StatusEffectType = mk("Found Factory");
		public static  IncubusBribed:StatusEffectType = mk("IncubusBribed");
		public static  FactorySuccubusDefeated:StatusEffectType = mk("FactorySuccubusDefeated");		
		public static  MaraeComplete:StatusEffectType = mk("Marae Complete");
		public static  MaraesLethicite:StatusEffectType = mk("Marae's Lethicite");
		public static  MaraesQuestStart:StatusEffectType = mk("Marae's Quest Start");
		public static  MetCorruptMarae:StatusEffectType = mk("Met Corrupt Marae");
		public static  MetMarae:StatusEffectType = mk("Met Marae");
		
		//Prisoner status effects.
		public static  PrisonCaptorEllyStatus:StatusEffectType = mk("prisonCaptorEllyStatus");
		public static  PrisonCaptorEllyQuest:StatusEffectType = mk("prisonCaptorEllyQuest");
		public static  PrisonCaptorEllyPet:StatusEffectType = mk("prisonCaptorEllyPet");
		public static  PrisonCaptorEllyBillie:StatusEffectType = mk("prisonCaptorEllyBillie");
		public static  PrisonCaptorEllyScruffy:StatusEffectType = mk("prisonCaptorEllyScruffy");
		public static  PrisonRestraints:StatusEffectType = mk("prisonRestraint");
		public static  PrisonCaptorEllyScratch:StatusEffectType = mk("prisonCaptorEllyScatch");
		
		public static  UmasMassage:StatusEffectType = mk("Uma's Massage"); //v1 = bonus index; v2 = bonus value; v3 = remaining time
		public static  Uniball:StatusEffectType = mk("Uniball");
		public static  UsedNaturalSelfStim:StatusEffectType = mk("used natural self-stim");
		public static  used_self_dash_stim:StatusEffectType = mk("used self-stim");
		public static  Victoria:StatusEffectType = mk("Victoria");
		public static  VoluntaryDemonpack:StatusEffectType = mk("Voluntary Demonpack");
		public static  WormOffer:StatusEffectType = mk("WormOffer");
		public static  WormPlugged:StatusEffectType = mk("worm plugged");
		public static  WormsHalf:StatusEffectType = mk("wormsHalf");
		public static  WormsOff:StatusEffectType = mk("wormsOff");
		public static  WormsOn:StatusEffectType = mk("wormsOn");
		public static  WandererDemon:StatusEffectType = mk("wanderer demon");
		public static  WandererHuman:StatusEffectType = mk("wanderer human");
		public static  Yara:StatusEffectType = mk("Yara");

		// monster
		public static  Attacks:StatusEffectType = mk("attacks");
		public static  BimboBrawl:StatusEffectType = mk("bimboBrawl");
		public static  BowCooldown:StatusEffectType = mk("Bow Cooldown");
		public static  BowDisabled:StatusEffectType = mk("Bow Disabled");
		public static  Charged:StatusEffectType = mk("Charged");
		public static  Climbed:StatusEffectType = mk("Climbed");
		public static  Concentration:StatusEffectType = mk("Concentration");
		public static  Constricted:StatusEffectType = mk("Constricted");
		public static  CoonWhip:StatusEffectType = mk("Coon Whip");
		public static  Counter:StatusEffectType = mk("Counter");
		public static  DomFight:StatusEffectType = mk("domfight");
		public static  DrankMinoCum:StatusEffectType = mk("drank mino cum");
		public static  DrankMinoCum2:StatusEffectType = mk("drank mino cum2")
		public static  Drunk:StatusEffectType = mk("Drunk");
		public static  Earthshield:StatusEffectType = mk("Earthshield");
		public static  Fear:StatusEffectType = mk("Fear");
		//public static const FearCounter:StatusEffectType = mk("FearCounter");
		public static  GenericRunDisabled:StatusEffectType = mk("Generic Run Disabled");
		public static  Gigafire:StatusEffectType = mk("Gigafire");
		public static  GottaOpenGift:StatusEffectType = mk("Gotta Open Gift");
		public static  HolliBurning:StatusEffectType = mk("Holli Burning");
		public static  Illusion:StatusEffectType = mk("Illusion");
		public static  ImpSkip:StatusEffectType = mk("ImpSkip");
		public static  ImpUber:StatusEffectType = mk("ImpUber");
		public static  JojoIsAssisting:StatusEffectType = mk("Jojo Is Assisting");
		public static  JojoPyre:StatusEffectType = mk("Jojo Pyre");
		public static  Keen:StatusEffectType = mk("keen");
		public static  Level:StatusEffectType = mk("level");
		public static  KitsuneFight:StatusEffectType = mk("Kitsune Fight");
		public static  LethicesRapeTentacles:StatusEffectType = mk("Lethices Rape Tentacles");
		public static  LustAura:StatusEffectType = mk("Lust Aura");
		public static  LustStick:StatusEffectType = mk("LustStick");
		public static  Milk:StatusEffectType = mk("milk");
		public static  MilkyUrta:StatusEffectType = mk("Milky Urta");
		public static  MinoMilk:StatusEffectType = mk("Mino Milk");
		public static  MinotaurEntangled:StatusEffectType = mk("Minotaur Entangled");

		public static  MissFirstRound:StatusEffectType = mk("miss first round");
		public static  NoLoot:StatusEffectType = mk("No Loot");
		public static  OnFire:StatusEffectType = mk("On Fire");
		public static  PCTailTangle:StatusEffectType = mk("PCTailTangle");
		public static  PeachLootLoss:StatusEffectType = mk("Peach Loot Loss");

		// @aimozg i don't know and do not fucking care if these two should be merged
		public static  PhyllaFight:StatusEffectType = mk("PhyllaFight");
		public static  phyllafight:StatusEffectType = mk("phyllafight");
		public static  Platoon:StatusEffectType = mk("platoon");
		public static  QueenBind:StatusEffectType = mk("QueenBind");
		// @aimozg HA HA HA
		public static  Round:StatusEffectType = mk("Round");
		public static  round:StatusEffectType = mk("round");
		public static  RunDisabled:StatusEffectType = mk("Run Disabled");
		public static  Shell:StatusEffectType = mk("Shell");
		public static  SirenSong:StatusEffectType = mk("Siren Song");
		public static  Spar:StatusEffectType = mk("spar");
		public static  Sparring:StatusEffectType = mk("sparring");
		public static  spiderfight:StatusEffectType = mk("spiderfight");
		public static  StunCooldown:StatusEffectType = mk("Stun Cooldown");
		public static  TentacleCoolDown:StatusEffectType = mk("TentacleCoolDown");
		public static  Timer:StatusEffectType = mk("Timer");
		public static  TimesBashed:StatusEffectType = mk("TimesBashed");
		public static  Uber:StatusEffectType = mk("Uber");
		public static  UrtaSecondWinded:StatusEffectType = mk("Urta Second Winded");
		public static  UsedTitsmother:StatusEffectType = mk("UsedTitsmother");
		public static  Vala:StatusEffectType = mk("vala");
		public static  Vapula:StatusEffectType = mk("Vapula");
		public static  WhipReady:StatusEffectType = mk("Whip Ready");
		public static  AikoLustPrank:StatusEffectType = mk("Aiko sex prank");
		public static  AikoHyper:StatusEffectType = mk("Aiko hyper attacks");
		public static  AikoArcaneArcher:StatusEffectType = mk("Aiko archer attacks");
		public static  YamataCanon:StatusEffectType = mk("Yamata Foxfire Canon");

		//Plantgirl
		public static  happy:StatusEffectType = mk("happy");
		public static  horny:StatusEffectType = mk("horny");
		public static  grouchy:StatusEffectType = mk("grouchy");
		
		// universal combat buffs
		public static  GenericCombatStrBuff:StatusEffectType  = CombatStrBuff.TYPE;
		public static  GenericCombatSpeBuff:StatusEffectType  = CombatSpeBuff.TYPE;
		public static  GenericCombatTouBuff:StatusEffectType  = CombatTouBuff.TYPE;
		public static  GenericCombatInteBuff:StatusEffectType = CombatInteBuff.TYPE;
		// combat
		public static  AcidSlap:StatusEffectType = mk("Acid Slap", CombatStatusEffect);
		public static  AkbalSpeed:StatusEffectType = AkbalSpeedDebuff.TYPE;
		public static  AmilyVenom:StatusEffectType = AmilyVenomDebuff.TYPE;
		public static  AnemoneVenom:StatusEffectType = AnemoneVenomDebuff.TYPE;
		public static  AttackDisabled:StatusEffectType = mk("Attack Disabled", CombatStatusEffect);
		public static  BasiliskCompulsion:StatusEffectType = mk("Basilisk Compulsion", CombatStatusEffect);
		public static  BasiliskSlow:StatusEffectType = BasiliskSlowDebuff.TYPE;
		public static  Berzerking:StatusEffectType = mk("Berzerking", CombatStatusEffect);
		public static  Blind:StatusEffectType = mk("Blind", CombatStatusEffect);
		public static  Bound:StatusEffectType = mk("Bound", CombatStatusEffect);
		public static  CalledShot:StatusEffectType = CalledShotDebuff.TYPE;
		public static  ChargeWeapon:StatusEffectType = mk("Charge Weapon", CombatStatusEffect);
		public static  Chokeslam:StatusEffectType = mk("Chokeslam", CombatStatusEffect);
		public static  Confusion:StatusEffectType          = mk("Confusion", CombatStatusEffect);
		public static  DemonSeed:StatusEffectType       = mk("DemonSeed", CombatStatusEffect);
		public static  Disarmed:StatusEffectType        = mk("Disarmed", CombatStatusEffect);
		public static  DriderKiss:StatusEffectType      = mk("Drider Kiss", CombatStatusEffect);
		public static  FirstAttack:StatusEffectType     = mk("FirstAttack", CombatStatusEffect);
		public static  GiantBoulder:StatusEffectType    = mk("Giant Boulder", CombatStatusEffect);
		public static  GiantGrabbed:StatusEffectType    = mk("Giant Grabbed", CombatStatusEffect);
		public static  GiantStrLoss:StatusEffectType    = GiantStrLossDebuff.TYPE;
		public static  GnollSpear:StatusEffectType      = GnollSpearDebuff.TYPE;
		public static  GooArmorBind:StatusEffectType    = mk("GooArmorBind", CombatStatusEffect);
		public static  GooArmorSilence:StatusEffectType = mk("GooArmorSilence", CombatStatusEffect);
		public static  GooBind:StatusEffectType         = mk("GooBind", CombatStatusEffect);
		public static  HarpyBind:StatusEffectType       = mk("HarpyBind", CombatStatusEffect);
		public static  HolliConstrict:StatusEffectType = mk("Holli Constrict", CombatStatusEffect);
		public static  InfestAttempted:StatusEffectType = mk("infestAttempted", CombatStatusEffect);
		public static  IsabellaStunned:StatusEffectType = mk("Isabella Stunned", CombatStatusEffect);
		public static  IzmaBleed:StatusEffectType = mk("Izma Bleed", CombatStatusEffect);
		public static  KissOfDeath:StatusEffectType = mk("Kiss of Death", CombatStatusEffect);
		public static  LizanBlowpipe:StatusEffectType = LizanBlowpipeDebuff.TYPE;
		public static  LustStones:StatusEffectType = mk("lust stones", CombatStatusEffect);
		public static  lustvenom:StatusEffectType = mk("lust venom", CombatStatusEffect);
		public static  Lustzerking:StatusEffectType = mk("Lustzerking", CombatStatusEffect);
		public static  Might:StatusEffectType = MightBuff.TYPE;
		public static  NagaBind:StatusEffectType = mk("Naga Bind", CombatStatusEffect);
		public static  NagaVenom:StatusEffectType = NagaVenomDebuff.TYPE;
		public static  NoFlee:StatusEffectType = mk("NoFlee", CombatStatusEffect);
		public static  ParalyzeVenom:StatusEffectType = ParalyzeVenomDebuff.TYPE;
		public static  PhysicalDisabled:StatusEffectType = mk("Physical Disabled", CombatStatusEffect);
		public static  Poison:StatusEffectType = mk("Poison", CombatStatusEffect);
		public static  Sandstorm:StatusEffectType = mk("sandstorm", CombatStatusEffect);
		public static  Sealed:StatusEffectType = mk("Sealed", CombatStatusEffect);
		public static  SheilaOil:StatusEffectType = mk("Sheila Oil", CombatStatusEffect);
		public static  Shielding:StatusEffectType = mk("Sheilding", CombatStatusEffect);
		public static  StoneLust:StatusEffectType = mk("Stone Lust", CombatStatusEffect);
		public static  Stunned:StatusEffectType = mk("Stunned", CombatStatusEffect);
		public static  TailWhip:StatusEffectType = mk("Tail Whip", CombatStatusEffect);
		public static  TemporaryHeat:StatusEffectType = mk("Temporary Heat", CombatStatusEffect);
		public static  TentacleBind:StatusEffectType = mk("TentacleBind", CombatStatusEffect);
		public static  ThroatPunch:StatusEffectType = mk("Throat Punch", CombatStatusEffect);
		public static  Titsmother:StatusEffectType = mk("Titsmother", CombatStatusEffect);
		public static  TwuWuv:StatusEffectType = mk("Twu Wuv", CombatStatusEffect);
		public static  UBERWEB:StatusEffectType = mk("UBERWEB", CombatStatusEffect);
		public static  Web:StatusEffectType = WebDebuff.TYPE;
		public static  WebSilence:StatusEffectType = mk("Web-Silence", CombatStatusEffect);
		public static  Whispered:StatusEffectType = mk("Whispered", CombatStatusEffect);
		public static  RemovedArmor:StatusEffectType = mk("Removed Armor", CombatStatusEffect);
		public static  JCLustLevel:StatusEffectType = mk("JC Lust Level", CombatStatusEffect);
		public static  MirroredAttack:StatusEffectType = mk("Mirrored Attack", CombatStatusEffect);
		public static  KnockedBack:StatusEffectType = mk("Knocked Back", CombatStatusEffect);
		public static  Tentagrappled:StatusEffectType = mk("Tentagrappled", CombatStatusEffect);
		public static  TentagrappleCooldown:StatusEffectType = mk("Tentagrapple Cooldown", CombatStatusEffect);
		public static  ShowerDotEffect:StatusEffectType = mk("Shower Dot Effect", CombatStatusEffect);
		public static  GardenerSapSpeed:StatusEffectType = GardenerSapSpeedDebuff.TYPE;
		public static  VineHealUsed:StatusEffectType = mk("Vine Heal Used", CombatStatusEffect);
		public static  DriderIncubusVenom:StatusEffectType = DriderIncubusVenomDebuff.TYPE;
		public static  PurpleHaze:StatusEffectType = mk("PurpleHaze", CombatStatusEffect);
		public static  TaintedMind:StatusEffectType = mk("Tainted Mind", CombatStatusEffect);
		public static  MinotaurKingMusk:StatusEffectType = mk("Minotaur King Musk", CombatStatusEffect);
		public static  MinotaurKingsTouch:StatusEffectType = mk("Minotaur Kings Touch", CombatStatusEffect);
		public static  PigbysHands:StatusEffectType = mk("Pigbys Hands", CombatStatusEffect);
		public static  WhipSilence:StatusEffectType = mk("Whip-Silence", CombatStatusEffect);
		public static  AikoLightningArrow:StatusEffectType = mk("Aiko archer attacks", CombatStatusEffect);
		public static  YamataEntwine:StatusEffectType = mk("Yamata Entwine", CombatStatusEffect);
		/**
		 * Creates status affect
		 */
		private static  mk(id: string, clazz:Class = undefined, arity: number = 1):StatusEffectType
		{
			return new StatusEffectType(id,clazz ? clazz : StatusEffect,arity);
		}
	}

