import { CombatStrBuff } from "./StatusEffects/Combat/CombatStrBuff";
import { CombatSpeBuff } from "./StatusEffects/Combat/CombatSpeBuff";
import { CombatTouBuff } from "./StatusEffects/Combat/CombatTouBuff";
import { CombatInteBuff } from "./StatusEffects/Combat/CombatInteBuff";
import { CombatStatusEffect } from "./StatusEffects/CombatStatusEffect";
import { AkbalSpeedDebuff } from "./StatusEffects/Combat/AkbalSpeedDebuff";
import { AmilyVenomDebuff } from "./StatusEffects/Combat/AmilyVenomDebuff";
import { AnemoneVenomDebuff } from "./StatusEffects/Combat/AnemoneVenomDebuff";
import { BasiliskSlowDebuff } from "./StatusEffects/Combat/BasiliskSlowDebuff";
import { CalledShotDebuff } from "./StatusEffects/Combat/CalledShotDebuff";
import { GiantStrLossDebuff } from "./StatusEffects/Combat/GiantStrLossDebuff";
import { GnollSpearDebuff } from "./StatusEffects/Combat/GnollSpearDebuff";
import { LizanBlowpipeDebuff } from "./StatusEffects/Combat/LizanBlowpipeDebuff";
import { MightBuff } from "./StatusEffects/Combat/MightBuff";
import { NagaVenomDebuff } from "./StatusEffects/Combat/NagaVenomDebuff";
import { ParalyzeVenomDebuff } from "./StatusEffects/Combat/ParalyzeVenomDebuff";
import { WebDebuff } from "./StatusEffects/Combat/WebDebuff";
import { GardenerSapSpeedDebuff } from "./StatusEffects/Combat/GardenerSapSpeedDebuff";
import { DriderIncubusVenomDebuff } from "./StatusEffects/Combat/DriderIncubusVenomDebuff";
import { StatusEffectType } from "./StatusEffectType";
import { StatusEffect } from "./StatusEffect";

/**
 * IMPORTANT NOTE: any You can rename the constants BUT NOT the string ids (they are stored in saves).
 */
export class StatusEffects {
    // Non-combat player perks
    public static AllNaturalOnaholeUsed = StatusEffects.mk("all-natural onahole used");
    public static AndysSmoke = StatusEffects.mk("Andy's Smoke"); // v1: Hours; v2: Speed; v3: Intelligence
    public static AteEgg = StatusEffects.mk("ateEgg");
    public static AnemoneArousal = StatusEffects.mk("Anemone Arousal");
    public static BimboChampagne = StatusEffects.mk("Bimbo Champagne");
    public static Birthed = StatusEffects.mk("Birthed");
    public static BirthedImps = StatusEffects.mk("Birthed Imps");
    public static BlackCatBeer = StatusEffects.mk("Black Cat Beer");
    public static BlackNipples = StatusEffects.mk("Black Nipples");
    public static BlowjobOn = StatusEffects.mk("BlowjobOn");
    public static BoatDiscovery = StatusEffects.mk("Boat Discovery");
    public static BonusACapacity = StatusEffects.mk("Bonus aCapacity");
    public static BonusVCapacity = StatusEffects.mk("Bonus vCapacity");
    public static BottledMilk = StatusEffects.mk("Bottled Milk");
    public static BreastsMilked = StatusEffects.mk("Breasts Milked");
    public static BSwordBroken = StatusEffects.mk("BSwordBroken");
    public static BuiltMilker = StatusEffects.mk("BUILT: Milker");
    public static BurpChanged = StatusEffects.mk("Burp Changed");
    public static ButtStretched = StatusEffects.mk("ButtStretched");
    public static CampAnemoneTrigger = StatusEffects.mk("Camp Anemone Trigger");
    public static CampMarble = StatusEffects.mk("Camp Marble");
    public static CampRathazul = StatusEffects.mk("Camp Rathazul");
    public static ClaraCombatRounds = StatusEffects.mk("Clara Combat Rounds");
    public static ClaraFoughtInCamp = StatusEffects.mk("Clara Fought In Camp");
    public static CockPumped = StatusEffects.mk("Cock Pumped");
    public static Contraceptives = StatusEffects.mk("Contraceptives");
    public static CuntStretched = StatusEffects.mk("CuntStretched"); // Used only for compatibility with old save files, replaced with attribute on vagina class
    public static DefenseCanopy = StatusEffects.mk("Defense: Canopy");
    public static DeluxeOnaholeUsed = StatusEffects.mk("deluxe onahole used");
    public static DogWarning = StatusEffects.mk("dog warning");
    public static DragonBreathBoost = StatusEffects.mk("Dragon Breath Boost");
    public static DragonBreathCooldown = StatusEffects.mk("Dragon Breath Cooldown");
    public static Dysfunction = StatusEffects.mk("dysfunction");
    public static Edryn = StatusEffects.mk("Edryn");
    public static Eggchest = StatusEffects.mk("eggchest");
    public static Eggs = StatusEffects.mk("eggs");
    public static EmberFuckCooldown = StatusEffects.mk("ember fuck cooldown");
    public static EmberMilk = StatusEffects.mk("Ember's Milk");
    public static EmberNapping = StatusEffects.mk("Ember Napping");
    public static EverRapedJojo = StatusEffects.mk("Ever Raped Jojo");
    public static Exgartuan = StatusEffects.mk("Exgartuan");
    public static ExploredDeepwoods = StatusEffects.mk("exploredDeepwoods");
    public static FaerieFemFuck = StatusEffects.mk("Faerie Fem Fuck");
    public static FaerieFucked = StatusEffects.mk("Faerie Fucked");
    public static FappedGenderless = StatusEffects.mk("fapped genderless");
    public static Feeder = StatusEffects.mk("Feeder");
    public static Fertilized = StatusEffects.mk("Fertilized");
    public static FetishOn = StatusEffects.mk("fetishON");
    public static FuckedMarble = StatusEffects.mk("FuckedMarble");
    public static Fullness = StatusEffects.mk("Fullness"); // Alternative to hunger
    public static Goojob = StatusEffects.mk("GOOJOB");
    public static GooStuffed = StatusEffects.mk("gooStuffed");
    public static Groundpound = StatusEffects.mk("Groundpound");
    public static HairdresserMeeting = StatusEffects.mk("hairdresser meeting");
    public static Hangover = StatusEffects.mk("Hangover");
    public static Heat = StatusEffects.mk("heat");
    public static HorseWarning = StatusEffects.mk("horse warning");
    public static ImmolationSpell = StatusEffects.mk("Immolation Spell");
    public static ImpGangBang = StatusEffects.mk("Imp GangBang");
    public static Infested = StatusEffects.mk("infested");
    public static IzmaBlowing = StatusEffects.mk("IzmaBlowing");
    public static IzumisPipeSmoke = StatusEffects.mk("Izumis Pipe Smoke");
    public static JerkingIzma = StatusEffects.mk("JerkingIzma");
    public static Jizzpants = StatusEffects.mk("Jizzpants");
    public static JojoMeditationCount = StatusEffects.mk("Jojo Meditation Count");
    public static JojoNightWatch = StatusEffects.mk("JojoNightWatch");
    public static JojoTFOffer = StatusEffects.mk("JojoTFOffer");
    public static Kelt = StatusEffects.mk("Kelt");
    public static KeltBJ = StatusEffects.mk("KeltBJ");
    public static KeltBadEndWarning = StatusEffects.mk("Kelt Bad End Warning");
    public static KeltOff = StatusEffects.mk("KeltOff");
    public static KnowsArouse = StatusEffects.mk("Knows Arouse");
    public static KnowsBlind = StatusEffects.mk("Knows Blind");
    public static KnowsCharge = StatusEffects.mk("Knows Charge");
    public static KnowsHeal = StatusEffects.mk("Knows Heal");
    public static KnowsMight = StatusEffects.mk("Knows Might");
    public static KnowsWhitefire = StatusEffects.mk("Knows Whitefire");
    public static KnowsBlackfire = StatusEffects.mk("Knows Blackfire");
    public static LactationEndurance = StatusEffects.mk("Lactation Endurance");
    public static LactationReduction = StatusEffects.mk("Lactation Reduction");
    public static LactationReduc0 = StatusEffects.mk("Lactation Reduc0");
    public static LactationReduc1 = StatusEffects.mk("Lactation Reduc1");
    public static LactationReduc2 = StatusEffects.mk("Lactation Reduc2");
    public static LactationReduc3 = StatusEffects.mk("Lactation Reduc3");
    public static LootEgg = StatusEffects.mk("lootEgg");
    public static LostVillagerSpecial = StatusEffects.mk("lostVillagerSpecial");
    public static Luststick = StatusEffects.mk("Luststick");
    public static LustStickApplied = StatusEffects.mk("Lust Stick Applied");
    public static LustyTongue = StatusEffects.mk("LustyTongue");
    public static MalonVisitedPostAddiction = StatusEffects.mk("Malon Visited Post Addiction");
    public static Marble = StatusEffects.mk("Marble");
    public static MarbleHasItem = StatusEffects.mk("MarbleHasItem");
    public static MarbleItemCooldown = StatusEffects.mk("MarbleItemCooldown");
    public static MarbleRapeAttempted = StatusEffects.mk("Marble Rape Attempted");
    public static MarblesMilk = StatusEffects.mk("Marbles Milk");
    public static MarbleSpecials = StatusEffects.mk("MarbleSpecials");
    public static MarbleWithdrawl = StatusEffects.mk("MarbleWithdrawl");
    public static Meditated = StatusEffects.mk("Meditated"); // DEPRECATED
    public static MeanToNaga = StatusEffects.mk("MeanToNaga");
    public static MeetWanderer = StatusEffects.mk("meet wanderer");
    public static MetRathazul = StatusEffects.mk("metRathazul");
    public static MetWorms = StatusEffects.mk("metWorms");
    public static MetWhitney = StatusEffects.mk("Met Whitney");
    public static Milked = StatusEffects.mk("Milked");
    public static MinoPlusCowgirl = StatusEffects.mk("Mino + Cowgirl");
    public static Naga = StatusEffects.mk("Naga");
    public static NakedOn = StatusEffects.mk("NakedOn");
    public static NoJojo = StatusEffects.mk("noJojo");
    public static NoMoreMarble = StatusEffects.mk("No More Marble");
    public static Oswald = StatusEffects.mk("Oswald");
    public static PlainOnaholeUsed = StatusEffects.mk("plain onahole used");
    public static PhoukaWhiskeyAffect = StatusEffects.mk("PhoukaWhiskeyAffect");
    public static PostAkbalSubmission = StatusEffects.mk("Post Akbal Submission");
    public static PostAnemoneBeatdown = StatusEffects.mk("Post Anemone Beatdown");
    public static PureCampJojo = StatusEffects.mk("PureCampJojo");
    public static RathazulArmor = StatusEffects.mk("RathazulArmor");
    public static RepeatSuccubi = StatusEffects.mk("repeatSuccubi");
    public static Rut = StatusEffects.mk("rut");
    public static SharkGirl = StatusEffects.mk("Shark-Girl");
    public static ShieldingSpell = StatusEffects.mk("Shielding Spell");
    public static SlimeCraving = StatusEffects.mk("Slime Craving");
    public static SlimeCravingFeed = StatusEffects.mk("Slime Craving Feed");
    public static SlimeCravingOutput = StatusEffects.mk("Slime Craving Output");
    public static SuccubiFirst = StatusEffects.mk("SuccubiFirst");
    public static SuccubiNight = StatusEffects.mk("succubiNight");
    public static TakenGroPlus = StatusEffects.mk("TakenGro+");
    public static TakenLactaid = StatusEffects.mk("TakenLactaid");
    public static Tamani = StatusEffects.mk("Tamani");									// Used only for compatibility with old save files, otherwise no longer in use
    public static TamaniFemaleEncounter = StatusEffects.mk("Tamani Female Encounter");	// Used only for compatibility with old save files, otherwise no longer in use
    public static TelAdre = StatusEffects.mk("Tel'Adre");
    public static TentacleBadEndCounter = StatusEffects.mk("TentacleBadEndCounter");
    public static TentacleJojo = StatusEffects.mk("Tentacle Jojo");
    public static TensionReleased = StatusEffects.mk("TensionReleased");
    public static TF2 = StatusEffects.mk("TF2");
    public static TookBlessedSword = StatusEffects.mk("Took Blessed Sword");

    // Old status plots. DEPRECATED, DO NOT USE. Currently cannot be removed without breaking existing saves.
    public static DungeonShutDown = StatusEffects.mk("DungeonShutDown");
    public static FactoryOmnibusDefeated = StatusEffects.mk("FactoryOmnibusDefeated");
    public static FactoryOverload = StatusEffects.mk("FactoryOverload");
    public static FactoryIncubusDefeated = StatusEffects.mk("FactoryIncubusDefeated");
    public static FoundFactory = StatusEffects.mk("Found Factory");
    public static IncubusBribed = StatusEffects.mk("IncubusBribed");
    public static FactorySuccubusDefeated = StatusEffects.mk("FactorySuccubusDefeated");
    public static MaraeComplete = StatusEffects.mk("Marae Complete");
    public static MaraesLethicite = StatusEffects.mk("Marae's Lethicite");
    public static MaraesQuestStart = StatusEffects.mk("Marae's Quest Start");
    public static MetCorruptMarae = StatusEffects.mk("Met Corrupt Marae");
    public static MetMarae = StatusEffects.mk("Met Marae");

    // Prisoner status effects.
    public static PrisonCaptorEllyStatus = StatusEffects.mk("prisonCaptorEllyStatus");
    public static PrisonCaptorEllyQuest = StatusEffects.mk("prisonCaptorEllyQuest");
    public static PrisonCaptorEllyPet = StatusEffects.mk("prisonCaptorEllyPet");
    public static PrisonCaptorEllyBillie = StatusEffects.mk("prisonCaptorEllyBillie");
    public static PrisonCaptorEllyScruffy = StatusEffects.mk("prisonCaptorEllyScruffy");
    public static PrisonRestraints = StatusEffects.mk("prisonRestraint");
    public static PrisonCaptorEllyScratch = StatusEffects.mk("prisonCaptorEllyScatch");

    public static UmasMassage = StatusEffects.mk("Uma's Massage"); // v1 = bonus index; v2 = bonus value; v3 = remaining time
    public static Uniball = StatusEffects.mk("Uniball");
    public static UsedNaturalSelfStim = StatusEffects.mk("used natural self-stim");
    public static used_self_dash_stim = StatusEffects.mk("used self-stim");
    public static Victoria = StatusEffects.mk("Victoria");
    public static VoluntaryDemonpack = StatusEffects.mk("Voluntary Demonpack");
    public static WormOffer = StatusEffects.mk("WormOffer");
    public static WormPlugged = StatusEffects.mk("worm plugged");
    public static WormsHalf = StatusEffects.mk("wormsHalf");
    public static WormsOff = StatusEffects.mk("wormsOff");
    public static WormsOn = StatusEffects.mk("wormsOn");
    public static WandererDemon = StatusEffects.mk("wanderer demon");
    public static WandererHuman = StatusEffects.mk("wanderer human");
    public static Yara = StatusEffects.mk("Yara");

    // monster
    public static Attacks = StatusEffects.mk("attacks");
    public static BimboBrawl = StatusEffects.mk("bimboBrawl");
    public static BowCooldown = StatusEffects.mk("Bow Cooldown");
    public static BowDisabled = StatusEffects.mk("Bow Disabled");
    public static Charged = StatusEffects.mk("Charged");
    public static Climbed = StatusEffects.mk("Climbed");
    public static Concentration = StatusEffects.mk("Concentration");
    public static Constricted = StatusEffects.mk("Constricted");
    public static CoonWhip = StatusEffects.mk("Coon Whip");
    public static Counter = StatusEffects.mk("Counter");
    public static DomFight = StatusEffects.mk("domfight");
    public static DrankMinoCum = StatusEffects.mk("drank mino cum");
    public static DrankMinoCum2 = StatusEffects.mk("drank mino cum2");
    public static Drunk = StatusEffects.mk("Drunk");
    public static Earthshield = StatusEffects.mk("Earthshield");
    public static Fear = StatusEffects.mk("Fear");
    // public static const FearCounter = mk("FearCounter");
    public static GenericRunDisabled = StatusEffects.mk("Generic Run Disabled");
    public static Gigafire = StatusEffects.mk("Gigafire");
    public static GottaOpenGift = StatusEffects.mk("Gotta Open Gift");
    public static HolliBurning = StatusEffects.mk("Holli Burning");
    public static Illusion = StatusEffects.mk("Illusion");
    public static ImpSkip = StatusEffects.mk("ImpSkip");
    public static ImpUber = StatusEffects.mk("ImpUber");
    public static JojoIsAssisting = StatusEffects.mk("Jojo Is Assisting");
    public static JojoPyre = StatusEffects.mk("Jojo Pyre");
    public static Keen = StatusEffects.mk("keen");
    public static Level = StatusEffects.mk("level");
    public static KitsuneFight = StatusEffects.mk("Kitsune Fight");
    public static LethicesRapeTentacles = StatusEffects.mk("Lethices Rape Tentacles");
    public static LustAura = StatusEffects.mk("Lust Aura");
    public static LustStick = StatusEffects.mk("LustStick");
    public static Milk = StatusEffects.mk("milk");
    public static MilkyUrta = StatusEffects.mk("Milky Urta");
    public static MinoMilk = StatusEffects.mk("Mino Milk");
    public static MinotaurEntangled = StatusEffects.mk("Minotaur Entangled");

    public static MissFirstRound = StatusEffects.mk("miss first round");
    public static NoLoot = StatusEffects.mk("No Loot");
    public static OnFire = StatusEffects.mk("On Fire");
    public static PCTailTangle = StatusEffects.mk("PCTailTangle");
    public static PeachLootLoss = StatusEffects.mk("Peach Loot Loss");

    // @aimozg i don't know and do not fucking care if these two should be merged
    public static PhyllaFight = StatusEffects.mk("PhyllaFight");
    public static phyllafight = StatusEffects.mk("phyllafight");
    public static Platoon = StatusEffects.mk("platoon");
    public static QueenBind = StatusEffects.mk("QueenBind");
    // @aimozg HA HA HA
    public static Round = StatusEffects.mk("Round");
    public static round = StatusEffects.mk("round");
    public static RunDisabled = StatusEffects.mk("Run Disabled");
    public static Shell = StatusEffects.mk("Shell");
    public static SirenSong = StatusEffects.mk("Siren Song");
    public static Spar = StatusEffects.mk("spar");
    public static Sparring = StatusEffects.mk("sparring");
    public static spiderfight = StatusEffects.mk("spiderfight");
    public static StunCooldown = StatusEffects.mk("Stun Cooldown");
    public static TentacleCoolDown = StatusEffects.mk("TentacleCoolDown");
    public static Timer = StatusEffects.mk("Timer");
    public static TimesBashed = StatusEffects.mk("TimesBashed");
    public static Uber = StatusEffects.mk("Uber");
    public static UrtaSecondWinded = StatusEffects.mk("Urta Second Winded");
    public static UsedTitsmother = StatusEffects.mk("UsedTitsmother");
    public static Vala = StatusEffects.mk("vala");
    public static Vapula = StatusEffects.mk("Vapula");
    public static WhipReady = StatusEffects.mk("Whip Ready");
    public static AikoLustPrank = StatusEffects.mk("Aiko sex prank");
    public static AikoHyper = StatusEffects.mk("Aiko hyper attacks");
    public static AikoArcaneArcher = StatusEffects.mk("Aiko archer attacks");
    public static YamataCanon = StatusEffects.mk("Yamata Foxfire Canon");

    // Plantgirl
    public static happy = StatusEffects.mk("happy");
    public static horny = StatusEffects.mk("horny");
    public static grouchy = StatusEffects.mk("grouchy");

    // universal combat buffs
    public static GenericCombatStrBuff = CombatStrBuff.TYPE;
    public static GenericCombatSpeBuff = CombatSpeBuff.TYPE;
    public static GenericCombatTouBuff = CombatTouBuff.TYPE;
    public static GenericCombatInteBuff = CombatInteBuff.TYPE;
    // combat
    public static AcidSlap = StatusEffects.mk("Acid Slap", CombatStatusEffect);
    public static AkbalSpeed = AkbalSpeedDebuff.TYPE;
    public static AmilyVenom = AmilyVenomDebuff.TYPE;
    public static AnemoneVenom = AnemoneVenomDebuff.TYPE;
    public static AttackDisabled = StatusEffects.mk("Attack Disabled", CombatStatusEffect);
    public static BasiliskCompulsion = StatusEffects.mk("Basilisk Compulsion", CombatStatusEffect);
    public static BasiliskSlow = BasiliskSlowDebuff.TYPE;
    public static Berzerking = StatusEffects.mk("Berzerking", CombatStatusEffect);
    public static Blind = StatusEffects.mk("Blind", CombatStatusEffect);
    public static Bound = StatusEffects.mk("Bound", CombatStatusEffect);
    public static CalledShot = CalledShotDebuff.TYPE;
    public static ChargeWeapon = StatusEffects.mk("Charge Weapon", CombatStatusEffect);
    public static Chokeslam = StatusEffects.mk("Chokeslam", CombatStatusEffect);
    public static Confusion = StatusEffects.mk("Confusion", CombatStatusEffect);
    public static DemonSeed = StatusEffects.mk("DemonSeed", CombatStatusEffect);
    public static Disarmed = StatusEffects.mk("Disarmed", CombatStatusEffect);
    public static DriderKiss = StatusEffects.mk("Drider Kiss", CombatStatusEffect);
    public static FirstAttack = StatusEffects.mk("FirstAttack", CombatStatusEffect);
    public static GiantBoulder = StatusEffects.mk("Giant Boulder", CombatStatusEffect);
    public static GiantGrabbed = StatusEffects.mk("Giant Grabbed", CombatStatusEffect);
    public static GiantStrLoss = GiantStrLossDebuff.TYPE;
    public static GnollSpear = GnollSpearDebuff.TYPE;
    public static GooArmorBind = StatusEffects.mk("GooArmorBind", CombatStatusEffect);
    public static GooArmorSilence = StatusEffects.mk("GooArmorSilence", CombatStatusEffect);
    public static GooBind = StatusEffects.mk("GooBind", CombatStatusEffect);
    public static HarpyBind = StatusEffects.mk("HarpyBind", CombatStatusEffect);
    public static HolliConstrict = StatusEffects.mk("Holli Constrict", CombatStatusEffect);
    public static InfestAttempted = StatusEffects.mk("infestAttempted", CombatStatusEffect);
    public static IsabellaStunned = StatusEffects.mk("Isabella Stunned", CombatStatusEffect);
    public static IzmaBleed = StatusEffects.mk("Izma Bleed", CombatStatusEffect);
    public static KissOfDeath = StatusEffects.mk("Kiss of Death", CombatStatusEffect);
    public static LizanBlowpipe = LizanBlowpipeDebuff.TYPE;
    public static LustStones = StatusEffects.mk("lust stones", CombatStatusEffect);
    public static lustvenom = StatusEffects.mk("lust venom", CombatStatusEffect);
    public static Lustzerking = StatusEffects.mk("Lustzerking", CombatStatusEffect);
    public static Might = MightBuff.TYPE;
    public static NagaBind = StatusEffects.mk("Naga Bind", CombatStatusEffect);
    public static NagaVenom = NagaVenomDebuff.TYPE;
    public static NoFlee = StatusEffects.mk("NoFlee", CombatStatusEffect);
    public static ParalyzeVenom = ParalyzeVenomDebuff.TYPE;
    public static PhysicalDisabled = StatusEffects.mk("Physical Disabled", CombatStatusEffect);
    public static Poison = StatusEffects.mk("Poison", CombatStatusEffect);
    public static Sandstorm = StatusEffects.mk("sandstorm", CombatStatusEffect);
    public static Sealed = StatusEffects.mk("Sealed", CombatStatusEffect);
    public static SheilaOil = StatusEffects.mk("Sheila Oil", CombatStatusEffect);
    public static Shielding = StatusEffects.mk("Sheilding", CombatStatusEffect);
    public static StoneLust = StatusEffects.mk("Stone Lust", CombatStatusEffect);
    public static Stunned = StatusEffects.mk("Stunned", CombatStatusEffect);
    public static TailWhip = StatusEffects.mk("Tail Whip", CombatStatusEffect);
    public static TemporaryHeat = StatusEffects.mk("Temporary Heat", CombatStatusEffect);
    public static TentacleBind = StatusEffects.mk("TentacleBind", CombatStatusEffect);
    public static ThroatPunch = StatusEffects.mk("Throat Punch", CombatStatusEffect);
    public static Titsmother = StatusEffects.mk("Titsmother", CombatStatusEffect);
    public static TwuWuv = StatusEffects.mk("Twu Wuv", CombatStatusEffect);
    public static UBERWEB = StatusEffects.mk("UBERWEB", CombatStatusEffect);
    public static Web = WebDebuff.TYPE;
    public static WebSilence = StatusEffects.mk("Web-Silence", CombatStatusEffect);
    public static Whispered = StatusEffects.mk("Whispered", CombatStatusEffect);
    public static RemovedArmor = StatusEffects.mk("Removed Armor", CombatStatusEffect);
    public static JCLustLevel = StatusEffects.mk("JC Lust Level", CombatStatusEffect);
    public static MirroredAttack = StatusEffects.mk("Mirrored Attack", CombatStatusEffect);
    public static KnockedBack = StatusEffects.mk("Knocked Back", CombatStatusEffect);
    public static Tentagrappled = StatusEffects.mk("Tentagrappled", CombatStatusEffect);
    public static TentagrappleCooldown = StatusEffects.mk("Tentagrapple Cooldown", CombatStatusEffect);
    public static ShowerDotEffect = StatusEffects.mk("Shower Dot Effect", CombatStatusEffect);
    public static GardenerSapSpeed = GardenerSapSpeedDebuff.TYPE;
    public static VineHealUsed = StatusEffects.mk("Vine Heal Used", CombatStatusEffect);
    public static DriderIncubusVenom = DriderIncubusVenomDebuff.TYPE;
    public static PurpleHaze = StatusEffects.mk("PurpleHaze", CombatStatusEffect);
    public static TaintedMind = StatusEffects.mk("Tainted Mind", CombatStatusEffect);
    public static MinotaurKingMusk = StatusEffects.mk("Minotaur King Musk", CombatStatusEffect);
    public static MinotaurKingsTouch = StatusEffects.mk("Minotaur Kings Touch", CombatStatusEffect);
    public static PigbysHands = StatusEffects.mk("Pigbys Hands", CombatStatusEffect);
    public static WhipSilence = StatusEffects.mk("Whip-Silence", CombatStatusEffect);
    public static AikoLightningArrow = StatusEffects.mk("Aiko archer attacks", CombatStatusEffect);
    public static YamataEntwine = StatusEffects.mk("Yamata Entwine", CombatStatusEffect);
    /**
     * Creates status affect
     */
    private static mk(id: string, clazz?: any, arity: number = 1) {
        return new StatusEffectType(id, clazz ? clazz : StatusEffect, arity);
    }
}
